language: java
branches:
  only:
    - master
    - develop
notifications:
  email:
    recipients:
      - matiramos8@msn.com
services:
  - mysql
script:
  #Test unitario y de integracion con cobertura (jacoco)
  - mvn verify
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Matthew-UTN_ide2-matias -Dsonar.login=$sonar
addons:
  sonarcloud:
    organization: "matthew-utn"